CREATE DATABASE api;

USE api;

CREATE TABLE `api`.`users` (
  `id` INT NOT NULL,
  `name` VARCHAR(63) NOT NULL,
  `email` VARCHAR(127) NOT NULL,
  `password` VARCHAR(127) NOT NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`));
